export const GET_ADDRESS_BOOK_SUCCESS = 'GET_ADDRESS_BOOK_SUCCESS';
export type T_ADDRESS_BOOK_SUCCESS = typeof GET_ADDRESS_BOOK_SUCCESS;

export const GET_ADDRESS_BOOK_FAILED = 'GET_ADDRESS_BOOK_FAILED';
export type T_GET_ADDRESS_BOOK_FAILED = typeof GET_ADDRESS_BOOK_FAILED;