export const GET_ADDRESS_BOOK_SUCCESS = 'GET_ADDRESS_BOOK_SUCCESS';
export type T_ADDRESS_BOOK_SUCCESS = typeof GET_ADDRESS_BOOK_SUCCESS;

export const GET_ADDRESS_BOOK_FAILED = 'GET_ADDRESS_BOOK_FAILED';
export type T_GET_ADDRESS_BOOK_FAILED = typeof GET_ADDRESS_BOOK_FAILED;

export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS_SUCCESS';
export type T_ADD_NEW_ADDRESS_SUCCESS = typeof ADD_NEW_ADDRESS_SUCCESS;

export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export type T_UPDATE_ADDRESS_SUCCESS = typeof UPDATE_ADDRESS_SUCCESS;