export const GET_NAVBAR_MENU_ITEMS_BEGIN = 'GET_NAVBAR_MENU_ITEMS_BEGIN';
export type T_GET_NAVBAR_MENU_ITEMS_BEGIN = typeof GET_NAVBAR_MENU_ITEMS_BEGIN;

export const GET_NAVBAR_MENU_ITEMS_FAILED = 'GET_NAVBAR_MENU_ITEMS_FAILED';
export type T_GET_NAVBAR_MENU_ITEMS_FAILED = typeof GET_NAVBAR_MENU_ITEMS_FAILED;

export const GET_NAVBAR_MENU_ITEMS_SUCCESS = 'GET_NAVBAR_MENU_ITEMS_SUCCESS';
export type T_GET_NAVBAR_MENU_ITEMS_SUCCESS = typeof GET_NAVBAR_MENU_ITEMS_SUCCESS;

export const GET_API_CONFIGS_BEGIN = 'GET_API_CONFIGS_BEGIN';
export type T_GET_API_CONFIGS_BEGIN = typeof GET_API_CONFIGS_BEGIN;

export const GET_API_CONFIGS_FAILED = 'GET_API_CONFIGS_FAILED';
export type T_GET_API_CONFIGS_FAILED = typeof GET_API_CONFIGS_FAILED;

export const GET_API_CONFIGS_SUCCESS = 'GET_API_CONFIGS_SUCCESS';
export type T_GET_API_CONFIGS_SUCCESS = typeof GET_API_CONFIGS_SUCCESS;
