export const INITIALIZE_AUTH_ON_LAUNCH = 'INITIALIZE_AUTH_ON_LAUNCH';
export type T_INITIALIZE_AUTH_ON_LAUNCH = typeof INITIALIZE_AUTH_ON_LAUNCH;

export const AUTHENTICATED = 'AUTHENTICATED';
export type T_AUTHENTICATED = typeof AUTHENTICATED;

export const AUTHENTICATION_VOID = 'AUTHENTICATION_VOID';
export type T_AUTHENTICATION_VOID = typeof AUTHENTICATION_VOID;
