export const INITIALIZE_AUTH_ON_LAUNCH = 'INITIALIZE_AUTH_ON_LAUNCH';
export type T_INITIALIZE_AUTH_ON_LAUNCH = typeof INITIALIZE_AUTH_ON_LAUNCH;

export const AUTHENTICATION_VOID = 'AUTHENTICATION_VOID';
export type T_AUTHENTICATION_VOID = typeof AUTHENTICATION_VOID;

export const ACTIVATE_ACCOUNT_GET_SECRET_CODE_REQUEST_STATUS_CODE = 'ACTIVATE_ACCOUNT_GET_SECRET_CODE_REQUEST_STATUS_CODE';
export type T_ACTIVATE_ACCOUNT_GET_SECRET_CODE_REQUEST_STATUS_CODE = typeof ACTIVATE_ACCOUNT_GET_SECRET_CODE_REQUEST_STATUS_CODE;

export const ACTIVATE_ACCOUNT_SECRET_CODE_SENT = 'ACTIVATE_ACCOUNT_SECRET_CODE_SENT';
export type T_ACTIVATE_ACCOUNT_SECRET_CODE_SENT = typeof ACTIVATE_ACCOUNT_SECRET_CODE_SENT;

export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export type T_ACTIVATE_ACCOUNT_SUCCESS = typeof ACTIVATE_ACCOUNT_SUCCESS;

export const ACTIVATE_ACCOUNT_FAILED = 'ACTIVATE_ACCOUNT_FAILED';
export type T_ACTIVATE_ACCOUNT_FAILED = typeof ACTIVATE_ACCOUNT_FAILED;

export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export type T_REGISTER_ACCOUNT_SUCCESS = typeof REGISTER_ACCOUNT_SUCCESS;

export const REGISTER_ACCOUNT_FAILED = 'REGISTER_ACCOUNT_FAILED';
export type T_REGISTER_ACCOUNT_FAILED = typeof REGISTER_ACCOUNT_FAILED;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type T_LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const PRE_LOGIN_SUCCESS = 'PRE_LOGIN_SUCCESS';
export type T_PRE_LOGIN_SUCCESS = typeof PRE_LOGIN_SUCCESS;

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export type T_LOGIN_FAILURE = typeof LOGIN_FAILURE;
