export const GET_PROFILE_INTERESTS_SUCCESS = 'GET_PROFILE_INTERESTS_SUCCESS';
export type T_GET_PROFILE_INTERESTS_SUCCESS = typeof GET_PROFILE_INTERESTS_SUCCESS;

export const GET_PROFILE_INTERESTS_FAILED = 'GET_PROFILE_INTERESTS_FAILED';
export type T_GET_PROFILE_INTERESTS_FAILED = typeof GET_PROFILE_INTERESTS_FAILED;