export const PREFETCH_LANGUAGE_ON_LAUNCH = 'PREFETCH_LANGUAGE_ON_LAUNCH';
export type T_PREFETCH_LANGUAGE_ON_LAUNCH = typeof PREFETCH_LANGUAGE_ON_LAUNCH;

export const CHANGE_SITE_LANGUAGE = 'CHANGE_SITE_LANGUAGE';
export type T_CHANGE_SITE_LANGUAGE = typeof CHANGE_SITE_LANGUAGE;