export const GET_LOCALITY_DATA_SUCCESS = 'GET_LOCALITY_DATA_SUCCESS';
export type T_GET_LOCALITY_DATA_SUCCESS = typeof GET_LOCALITY_DATA_SUCCESS;

export const GET_LOCALITY_DATA_FAILED = 'GET_LOCALITY_DATA_FAILED';
export type T_GET_LOCALITY_DATA_FAILED = typeof GET_LOCALITY_DATA_FAILED;