export const SET_STAGE = 'SET_STAGE';
export type T_SET_STAGE = typeof SET_STAGE;

export const REMOVE_STAGE = 'REMOVE_STAGE';
export type T_REMOVE_STAGE = typeof REMOVE_STAGE;

export const REMOVE_STAGES_MANY = 'REMOVE_STAGE_MANY';
export type T_REMOVE_STAGE_MANY = typeof REMOVE_STAGES_MANY;

export const CLEAR_ALL_STAGE = 'CLEAR_ALL_STAGE';
export type T_CLEAR_ALL_STAGE = typeof CLEAR_ALL_STAGE;

export const DANGEROUSLY_CLEAR_ALL_STAGE = 'DANGEROUSLY_CLEAR_ALL_STAGE';
export type T_DANGEROUSLY_CLEAR_ALL_STAGE = typeof DANGEROUSLY_CLEAR_ALL_STAGE;

export const SET_ERROR_DATA = 'SET_ERROR_DATA';
export type T_SET_ERROR_DATA = typeof SET_ERROR_DATA;

export const REMOVE_ERROR_DATA = 'REMOVE_ERROR_DATA';
export type T_REMOVE_ERROR_DATA = typeof REMOVE_ERROR_DATA;
