export const LOAD_DEFAULT_THEME = 'LOAD_DEFAULT_THEME';
export type T_LOAD_DEFAULT_THEME = typeof LOAD_DEFAULT_THEME;

export const SET_DEFAULT_THEME = 'SET_DEFAULT_THEME';
export type T_SET_DEFAULT_THEME = typeof SET_DEFAULT_THEME;
